/* =====================================================================
   traduzioni.js — testi della pagina di richiesta posizione
   =====================================================================
   Le stesse dieci lingue dei messaggi del portale: se la sala operativa
   manda il messaggio in inglese, il link apre la pagina in inglese.
   La lingua arriva dal parametro «lingua» dell'indirizzo; se manca o non
   è prevista si usa l'italiano.

   Per aggiungere una lingua basta aggiungere una voce qui: la pagina
   costruisce da sola il selettore in fondo.
   ===================================================================== */
window.TRADUZIONI = {

  it: { nome: "Italiano",
    titolo: "Vigili del Fuoco",
    comando: "Sala Operativa di {comando}",
    intestazione: "Invia la tua posizione",
    spiegazione: "La sala operativa ha bisogno di sapere dove ti trovi. Premi il pulsante qui sotto e consenti al telefono di comunicare la posizione.",
    pronto: "Premi il pulsante per rilevare la posizione.",
    rilevo: "Rilevamento in corso: tieni il telefono fermo e all'aperto…",
    tentativo: "tentativo {n} di {tot}",
    invio: "Posizione rilevata, la sto inviando alla sala operativa…",
    inviata: "Posizione inviata alla sala operativa. Resta dove sei e tieni libera la linea.",
    inviate_n: "{n} posizioni inviate alla sala operativa. Resta dove sei e tieni libera la linea.",
    non_inviata: "Posizione rilevata, ma non è stato possibile inviarla. Comunica a voce le coordinate qui sopra.",
    negato: "Non hai dato il consenso alla posizione. Consentilo nelle impostazioni del browser e riprova.",
    non_disponibile: "Il telefono non riesce a determinare la posizione. Esci all'aperto e riprova.",
    scaduto: "Tempo scaduto nella ricerca del segnale. Riprova restando all'aperto.",
    non_supportato: "Questo browser non è in grado di rilevare la posizione. Comunica a voce dove ti trovi.",
    rileva: "Rileva la mia posizione",
    mappa: "Vedi sulla mappa",
    riprova: "Riprova",
    precisione: "precisione circa {metri} metri",
    precisione_scarsa: "precisione circa {metri} metri — poco accurata, riprova all'aperto",
    emergenza_su: "Per le emergenze chiama sempre",
    emergenza_giu: "Questa pagina non sostituisce la chiamata di soccorso.",
    aiuto_titolo: "Se la posizione non viene rilevata",
    aiuto_1: "Controlla che il GPS del telefono sia acceso.",
    aiuto_2: "Consenti al browser di accedere alla posizione quando lo chiede.",
    aiuto_3: "Esci all'aperto, lontano da muri e tettoie, e attendi qualche secondo.",
    aiuto_4: "Se non riesci, resta in linea e comunica a voce dove ti trovi.",
    piede: "Corpo Nazionale dei Vigili del Fuoco",
    privacy: "La posizione viene usata solo per raggiungerti e non per altri scopi.",
  },

  en: { nome: "English",
    titolo: "Fire and Rescue Service",
    comando: "{comando} Control Room",
    intestazione: "Send your location",
    spiegazione: "The control room needs to know where you are. Press the button below and allow your phone to share your location.",
    pronto: "Press the button to detect your location.",
    rilevo: "Detecting your location: hold the phone still, outdoors if possible…",
    tentativo: "attempt {n} of {tot}",
    invio: "Location detected, sending it to the control room…",
    inviata: "Location sent to the control room. Stay where you are and keep the line free.",
    inviate_n: "{n} locations sent to the control room. Stay where you are and keep the phone line free.",
    non_inviata: "Location detected, but it could not be sent. Please read the coordinates above out loud over the phone.",
    negato: "Location permission was denied. Allow it in your browser settings and try again.",
    non_disponibile: "Your phone cannot determine the location. Move outdoors and try again.",
    scaduto: "Timed out while searching for a signal. Try again outdoors.",
    non_supportato: "This browser cannot detect your location. Please describe where you are over the phone.",
    rileva: "Detect my location",
    mappa: "View on the map",
    riprova: "Try again",
    precisione: "accurate to about {metri} metres",
    precisione_scarsa: "accurate to about {metri} metres — not very precise, try again outdoors",
    emergenza_su: "For emergencies always call",
    emergenza_giu: "This page does not replace an emergency call.",
    aiuto_titolo: "If your location is not detected",
    aiuto_1: "Check that your phone's GPS is switched on.",
    aiuto_2: "Allow the browser to access your location when asked.",
    aiuto_3: "Go outdoors, away from walls and roofs, and wait a few seconds.",
    aiuto_4: "If it still fails, stay on the line and describe where you are.",
    piede: "Italian National Fire and Rescue Service",
    privacy: "Your location is used only to reach you, for no other purpose.",
  },

  fr: { nome: "Français",
    titolo: "Sapeurs-Pompiers",
    comando: "Salle opérationnelle de {comando}",
    intestazione: "Envoyez votre position",
    spiegazione: "La salle opérationnelle a besoin de savoir où vous êtes. Appuyez sur le bouton ci-dessous et autorisez votre téléphone à communiquer la position.",
    pronto: "Appuyez sur le bouton pour détecter la position.",
    rilevo: "Détection en cours : gardez le téléphone immobile, si possible à l'extérieur…",
    tentativo: "tentative {n} sur {tot}",
    invio: "Position détectée, envoi à la salle opérationnelle…",
    inviata: "Position envoyée à la salle opérationnelle. Restez où vous êtes et laissez la ligne libre.",
    inviate_n: "{n} positions envoyées au centre opérationnel. Restez où vous êtes et laissez la ligne libre.",
    non_inviata: "Position détectée, mais l'envoi a échoué. Communiquez les coordonnées ci-dessus par téléphone.",
    negato: "L'autorisation de localisation a été refusée. Autorisez-la dans les réglages du navigateur et réessayez.",
    non_disponibile: "Le téléphone n'arrive pas à déterminer la position. Sortez à l'extérieur et réessayez.",
    scaduto: "Délai dépassé lors de la recherche du signal. Réessayez à l'extérieur.",
    non_supportato: "Ce navigateur ne peut pas détecter la position. Indiquez de vive voix où vous êtes.",
    rileva: "Détecter ma position",
    mappa: "Voir sur la carte",
    riprova: "Réessayer",
    precisione: "précision d'environ {metri} mètres",
    precisione_scarsa: "précision d'environ {metri} mètres — peu précise, réessayez à l'extérieur",
    emergenza_su: "Pour les urgences appelez toujours le",
    emergenza_giu: "Cette page ne remplace pas un appel de secours.",
    aiuto_titolo: "Si la position n'est pas détectée",
    aiuto_1: "Vérifiez que le GPS du téléphone est activé.",
    aiuto_2: "Autorisez le navigateur à accéder à la position lorsqu'il le demande.",
    aiuto_3: "Sortez à l'extérieur, loin des murs et des toits, et attendez quelques secondes.",
    aiuto_4: "Si cela ne marche pas, restez en ligne et décrivez où vous êtes.",
    piede: "Corps National des Sapeurs-Pompiers",
    privacy: "La position sert uniquement à vous rejoindre, à aucune autre fin.",
  },

  de: { nome: "Deutsch",
    titolo: "Feuerwehr",
    comando: "Leitstelle {comando}",
    intestazione: "Senden Sie Ihren Standort",
    spiegazione: "Die Leitstelle muss wissen, wo Sie sind. Drücken Sie die Taste unten und erlauben Sie dem Telefon, den Standort zu übermitteln.",
    pronto: "Drücken Sie die Taste, um den Standort zu ermitteln.",
    rilevo: "Standort wird ermittelt: Telefon ruhig halten, möglichst im Freien…",
    tentativo: "Versuch {n} von {tot}",
    invio: "Standort ermittelt, wird an die Leitstelle gesendet…",
    inviata: "Standort an die Leitstelle gesendet. Bleiben Sie, wo Sie sind, und halten Sie die Leitung frei.",
    inviate_n: "{n} Standorte an die Leitstelle gesendet. Bleiben Sie, wo Sie sind, und halten Sie die Leitung frei.",
    non_inviata: "Standort ermittelt, konnte aber nicht gesendet werden. Lesen Sie die Koordinaten oben am Telefon vor.",
    negato: "Die Standortfreigabe wurde verweigert. Erlauben Sie sie in den Browsereinstellungen und versuchen Sie es erneut.",
    non_disponibile: "Das Telefon kann den Standort nicht bestimmen. Gehen Sie ins Freie und versuchen Sie es erneut.",
    scaduto: "Zeitüberschreitung bei der Signalsuche. Versuchen Sie es im Freien erneut.",
    non_supportato: "Dieser Browser kann den Standort nicht ermitteln. Beschreiben Sie telefonisch, wo Sie sind.",
    rileva: "Meinen Standort ermitteln",
    mappa: "Auf der Karte ansehen",
    riprova: "Erneut versuchen",
    precisione: "Genauigkeit etwa {metri} Meter",
    precisione_scarsa: "Genauigkeit etwa {metri} Meter — wenig genau, bitte im Freien erneut versuchen",
    emergenza_su: "Im Notfall rufen Sie immer",
    emergenza_giu: "Diese Seite ersetzt keinen Notruf.",
    aiuto_titolo: "Wenn der Standort nicht ermittelt wird",
    aiuto_1: "Prüfen Sie, ob das GPS des Telefons eingeschaltet ist.",
    aiuto_2: "Erlauben Sie dem Browser den Zugriff auf den Standort.",
    aiuto_3: "Gehen Sie ins Freie, weg von Mauern und Dächern, und warten Sie einige Sekunden.",
    aiuto_4: "Wenn es nicht klappt, bleiben Sie in der Leitung und beschreiben Sie Ihren Standort.",
    piede: "Nationales Feuerwehrkorps Italien",
    privacy: "Der Standort wird nur verwendet, um Sie zu erreichen.",
  },

  es: { nome: "Español",
    titolo: "Bomberos",
    comando: "Sala Operativa de {comando}",
    intestazione: "Envía tu ubicación",
    spiegazione: "La sala operativa necesita saber dónde estás. Pulsa el botón de abajo y permite que el teléfono comunique la ubicación.",
    pronto: "Pulsa el botón para detectar la ubicación.",
    rilevo: "Detectando la ubicación: mantén el teléfono quieto, a ser posible al aire libre…",
    tentativo: "intento {n} de {tot}",
    invio: "Ubicación detectada, enviándola a la sala operativa…",
    inviata: "Ubicación enviada a la sala operativa. Quédate donde estás y mantén la línea libre.",
    inviate_n: "{n} ubicaciones enviadas a la sala de operaciones. Quédate donde estás y deja la línea libre.",
    non_inviata: "Ubicación detectada, pero no se ha podido enviar. Comunica de viva voz las coordenadas de arriba.",
    negato: "No has dado permiso de ubicación. Permítelo en los ajustes del navegador e inténtalo de nuevo.",
    non_disponibile: "El teléfono no consigue determinar la ubicación. Sal al aire libre e inténtalo de nuevo.",
    scaduto: "Se ha agotado el tiempo buscando señal. Inténtalo de nuevo al aire libre.",
    non_supportato: "Este navegador no puede detectar la ubicación. Indica de viva voz dónde estás.",
    rileva: "Detectar mi ubicación",
    mappa: "Ver en el mapa",
    riprova: "Reintentar",
    precisione: "precisión de unos {metri} metros",
    precisione_scarsa: "precisión de unos {metri} metros — poco precisa, inténtalo al aire libre",
    emergenza_su: "Para emergencias llama siempre al",
    emergenza_giu: "Esta página no sustituye una llamada de emergencia.",
    aiuto_titolo: "Si no se detecta la ubicación",
    aiuto_1: "Comprueba que el GPS del teléfono esté encendido.",
    aiuto_2: "Permite al navegador acceder a la ubicación cuando lo pida.",
    aiuto_3: "Sal al aire libre, lejos de muros y techos, y espera unos segundos.",
    aiuto_4: "Si no lo consigues, permanece en línea y describe dónde estás.",
    piede: "Cuerpo Nacional de Bomberos de Italia",
    privacy: "La ubicación se usa solo para llegar hasta ti, no para otros fines.",
  },

  ro: { nome: "Română",
    titolo: "Pompierii",
    comando: "Dispeceratul {comando}",
    intestazione: "Trimite poziția ta",
    spiegazione: "Dispeceratul trebuie să știe unde te afli. Apasă butonul de mai jos și permite telefonului să comunice poziția.",
    pronto: "Apasă butonul pentru a detecta poziția.",
    rilevo: "Se detectează poziția: ține telefonul nemișcat, dacă se poate afară…",
    tentativo: "încercarea {n} din {tot}",
    invio: "Poziție detectată, se trimite la dispecerat…",
    inviata: "Poziția a fost trimisă la dispecerat. Rămâi unde ești și ține linia liberă.",
    inviate_n: "{n} poziții trimise la centrul operativ. Rămâi unde ești și lasă linia liberă.",
    non_inviata: "Poziția a fost detectată, dar nu a putut fi trimisă. Comunică verbal coordonatele de mai sus.",
    negato: "Nu ai permis accesul la poziție. Permite-l în setările navigatorului și încearcă din nou.",
    non_disponibile: "Telefonul nu reușește să determine poziția. Ieși afară și încearcă din nou.",
    scaduto: "Timpul a expirat în căutarea semnalului. Încearcă din nou afară.",
    non_supportato: "Acest navigator nu poate detecta poziția. Spune verbal unde te afli.",
    rileva: "Detectează poziția mea",
    mappa: "Vezi pe hartă",
    riprova: "Încearcă din nou",
    precisione: "precizie de circa {metri} metri",
    precisione_scarsa: "precizie de circa {metri} metri — puțin precisă, încearcă afară",
    emergenza_su: "Pentru urgențe sună întotdeauna la",
    emergenza_giu: "Această pagină nu înlocuiește apelul de urgență.",
    aiuto_titolo: "Dacă poziția nu este detectată",
    aiuto_1: "Verifică dacă GPS-ul telefonului este pornit.",
    aiuto_2: "Permite navigatorului să acceseze poziția când o cere.",
    aiuto_3: "Ieși afară, departe de ziduri și acoperișuri, și așteaptă câteva secunde.",
    aiuto_4: "Dacă nu reușești, rămâi pe linie și descrie unde te afli.",
    piede: "Corpul Național al Pompierilor din Italia",
    privacy: "Poziția este folosită doar pentru a ajunge la tine.",
  },

  sq: { nome: "Shqip",
    titolo: "Zjarrfikësit",
    comando: "Salla Operative e {comando}",
    intestazione: "Dërgo pozicionin tënd",
    spiegazione: "Salla operative ka nevojë të dijë ku ndodhesh. Shtyp butonin më poshtë dhe lejo telefonin të komunikojë pozicionin.",
    pronto: "Shtyp butonin për të gjetur pozicionin.",
    rilevo: "Po gjendet pozicioni: mbaje telefonin pa lëvizur, nëse mundesh jashtë…",
    tentativo: "përpjekja {n} nga {tot}",
    invio: "Pozicioni u gjet, po dërgohet te salla operative…",
    inviata: "Pozicioni u dërgua te salla operative. Qëndro aty ku je dhe mbaje linjën të lirë.",
    inviate_n: "{n} pozicione u dërguan në sallën operative. Qëndro ku je dhe lëre linjën të lirë.",
    non_inviata: "Pozicioni u gjet, por nuk u dërgua dot. Komunikoji me zë koordinatat më sipër.",
    negato: "Nuk ke dhënë leje për pozicionin. Lejoje te cilësimet e shfletuesit dhe provo sërish.",
    non_disponibile: "Telefoni nuk arrin të përcaktojë pozicionin. Dil jashtë dhe provo sërish.",
    scaduto: "Koha skadoi gjatë kërkimit të sinjalit. Provo sërish jashtë.",
    non_supportato: "Ky shfletues nuk e gjen dot pozicionin. Thuaj me zë ku ndodhesh.",
    rileva: "Gjej pozicionin tim",
    mappa: "Shiko në hartë",
    riprova: "Provo sërish",
    precisione: "saktësi rreth {metri} metra",
    precisione_scarsa: "saktësi rreth {metri} metra — pak e saktë, provo jashtë",
    emergenza_su: "Për emergjencat telefono gjithmonë",
    emergenza_giu: "Kjo faqe nuk zëvendëson thirrjen e emergjencës.",
    aiuto_titolo: "Nëse pozicioni nuk gjendet",
    aiuto_1: "Kontrollo që GPS-i i telefonit të jetë ndezur.",
    aiuto_2: "Lejo shfletuesin të përdorë pozicionin kur e kërkon.",
    aiuto_3: "Dil jashtë, larg mureve dhe çative, dhe prit disa sekonda.",
    aiuto_4: "Nëse nuk ia del, qëndro në linjë dhe përshkruaj ku ndodhesh.",
    piede: "Trupi Kombëtar i Zjarrfikësve të Italisë",
    privacy: "Pozicioni përdoret vetëm për të ardhur te ti.",
  },

  uk: { nome: "Українська",
    titolo: "Пожежна служба",
    comando: "Оперативний центр {comando}",
    intestazione: "Надішліть своє місцезнаходження",
    spiegazione: "Оперативному центру потрібно знати, де ви. Натисніть кнопку нижче й дозвольте телефону передати місцезнаходження.",
    pronto: "Натисніть кнопку, щоб визначити місцезнаходження.",
    rilevo: "Визначення місцезнаходження: тримайте телефон нерухомо, по можливості надворі…",
    tentativo: "спроба {n} з {tot}",
    invio: "Місцезнаходження визначено, надсилаємо до оперативного центру…",
    inviata: "Місцезнаходження надіслано. Залишайтеся на місці й тримайте лінію вільною.",
    inviate_n: "{n} місця надіслано до оперативного центру. Залишайтеся на місці та не займайте лінію.",
    non_inviata: "Місцезнаходження визначено, але надіслати не вдалося. Продиктуйте координати вище по телефону.",
    negato: "Доступ до місцезнаходження заборонено. Дозвольте його в налаштуваннях браузера й спробуйте ще раз.",
    non_disponibile: "Телефон не може визначити місцезнаходження. Вийдіть надвір і спробуйте ще раз.",
    scaduto: "Час пошуку сигналу вичерпано. Спробуйте ще раз надворі.",
    non_supportato: "Цей браузер не може визначити місцезнаходження. Опишіть голосом, де ви.",
    rileva: "Визначити моє місцезнаходження",
    mappa: "Подивитися на карті",
    riprova: "Спробувати ще раз",
    precisione: "точність приблизно {metri} метрів",
    precisione_scarsa: "точність приблизно {metri} метрів — невисока, спробуйте надворі",
    emergenza_su: "У разі небезпеки завжди телефонуйте",
    emergenza_giu: "Ця сторінка не замінює виклик рятувальників.",
    aiuto_titolo: "Якщо місцезнаходження не визначається",
    aiuto_1: "Перевірте, чи увімкнено GPS на телефоні.",
    aiuto_2: "Дозвольте браузеру доступ до місцезнаходження.",
    aiuto_3: "Вийдіть надвір, подалі від стін і дахів, і зачекайте кілька секунд.",
    aiuto_4: "Якщо не вдається, залишайтеся на лінії й опишіть, де ви.",
    piede: "Національний корпус пожежної охорони Італії",
    privacy: "Місцезнаходження використовується лише щоб вас знайти.",
  },

  zh: { nome: "中文",
    titolo: "消防救援",
    comando: "{comando} 指挥中心",
    intestazione: "发送您的位置",
    spiegazione: "指挥中心需要知道您在哪里。请按下方按钮，并允许手机发送位置。",
    pronto: "请按按钮以获取位置。",
    rilevo: "正在获取位置：请拿稳手机，尽量在室外…",
    tentativo: "第 {n} 次尝试，共 {tot} 次",
    invio: "已获取位置，正在发送到指挥中心…",
    inviata: "位置已发送到指挥中心。请留在原地，保持电话畅通。",
    inviate_n: "已向指挥中心发送 {n} 个位置。请留在原地，并保持电话线路畅通。",
    non_inviata: "已获取位置，但发送失败。请通过电话口述上方的坐标。",
    negato: "位置权限被拒绝。请在浏览器设置中允许后重试。",
    non_disponibile: "手机无法确定位置。请到室外后重试。",
    scaduto: "搜索信号超时。请在室外重试。",
    non_supportato: "此浏览器无法获取位置。请通过电话说明您的位置。",
    rileva: "获取我的位置",
    mappa: "在地图上查看",
    riprova: "重试",
    precisione: "精度约 {metri} 米",
    precisione_scarsa: "精度约 {metri} 米 — 不够准确，请到室外重试",
    emergenza_su: "紧急情况请始终拨打",
    emergenza_giu: "本页面不能代替紧急呼救电话。",
    aiuto_titolo: "如果无法获取位置",
    aiuto_1: "请检查手机的 GPS 是否已开启。",
    aiuto_2: "当浏览器询问时，请允许访问位置。",
    aiuto_3: "请到室外，远离墙壁和屋顶，等待几秒钟。",
    aiuto_4: "如果仍然不行，请保持通话并说明您所在的位置。",
    piede: "意大利国家消防救援队",
    privacy: "位置信息仅用于找到您，不作他用。",
  },

  ar: { nome: "العربية", rtl: true,
    titolo: "الإطفاء والإنقاذ",
    comando: "غرفة عمليات {comando}",
    intestazione: "أرسل موقعك",
    spiegazione: "تحتاج غرفة العمليات إلى معرفة مكانك. اضغط الزر أدناه واسمح للهاتف بإرسال الموقع.",
    pronto: "اضغط الزر لتحديد الموقع.",
    rilevo: "جارٍ تحديد الموقع: أمسك الهاتف ثابتًا، في الخارج إن أمكن…",
    tentativo: "المحاولة {n} من {tot}",
    invio: "تم تحديد الموقع، جارٍ إرساله إلى غرفة العمليات…",
    inviata: "تم إرسال الموقع إلى غرفة العمليات. ابقَ مكانك واترك الخط متاحًا.",
    inviate_n: "تم إرسال {n} مواقع إلى غرفة العمليات. ابقَ في مكانك واترك الخط مفتوحًا.",
    non_inviata: "تم تحديد الموقع لكن تعذّر إرساله. أملِ الإحداثيات أعلاه عبر الهاتف.",
    negato: "تم رفض إذن الموقع. اسمح به في إعدادات المتصفح ثم أعد المحاولة.",
    non_disponibile: "لا يستطيع الهاتف تحديد الموقع. اخرج إلى العراء وأعد المحاولة.",
    scaduto: "انتهت المهلة أثناء البحث عن الإشارة. أعد المحاولة في العراء.",
    non_supportato: "هذا المتصفح لا يستطيع تحديد الموقع. اشرح مكانك عبر الهاتف.",
    rileva: "حدّد موقعي",
    mappa: "عرض على الخريطة",
    riprova: "أعد المحاولة",
    precisione: "دقة نحو {metri} متر",
    precisione_scarsa: "دقة نحو {metri} متر — غير دقيقة، أعد المحاولة في العراء",
    emergenza_su: "في حالات الطوارئ اتصل دائمًا بـ",
    emergenza_giu: "هذه الصفحة لا تغني عن الاتصال بالطوارئ.",
    aiuto_titolo: "إذا لم يتم تحديد الموقع",
    aiuto_1: "تأكد من تشغيل نظام تحديد المواقع في الهاتف.",
    aiuto_2: "اسمح للمتصفح بالوصول إلى الموقع عند طلبه.",
    aiuto_3: "اخرج إلى العراء بعيدًا عن الجدران والأسقف وانتظر بضع ثوانٍ.",
    aiuto_4: "إذا لم تنجح، ابقَ على الخط واشرح أين أنت.",
    piede: "الفيلق الوطني الإيطالي للإطفاء والإنقاذ",
    privacy: "يُستخدم الموقع فقط للوصول إليك، ولا لأي غرض آخر.",
  },
};
